export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_ERROR = 'AUTH_ERROR';
//login type
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
//register types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_COMPANY_ERROR = "REGISTER_COMPANY_ERROR";
//confirm email
export const SEND_EMAIL_DELETE = 'SEND_EMAIL_DELETE';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const EMAIL_CONFIRM_ERROR = 'EMAIL_CONFIRM_ERROR';
//get companies types
export const COMPANIES_LOAD_REQUEST = 'COMPANIES_LOAD_REQUEST';
export const COMPANIES_LOADED_SUCCESS = 'COMPANIES_LOAD_SUCCESS';
export const COMPANIES_LOADED_ERROR = 'COMPANIES_LOAD_ERROR';
//company types
export const COMPANY_LOAD_REQUEST = 'COMPANY_LOAD_REQUEST';
export const COMPANY_LOADED_SUCCESS = 'COMPANY_LOAD_SUCCESS';
export const SAVE_COMPANY_REGISTER = 'SAVE_COMPANY_REGISTER';
export const COMPANY_LOADED_ERROR = 'COMPANY_LOAD_ERROR';
//reviews load types
export const REVIEWS_LIST_LOAD_REQUEST = 'REVIEWS_LIST_LOAD_REQUEST';
export const REVIEWS_LIST_LOADED_SUCCESS = 'REVIEWS_LIST_LOAD_SUCCESS';
export const REVIEWS_LIST_LOADED_ERROR = 'REVIEWS_LIST_LOAD_ERROR';
//review create types
export const REVIEW_CREATE_REQUEST = 'REVIEW_CREATE_REQUEST';
export const REVIEW_CREATED_SUCCESS = 'REVIEW_CREATE_SUCCESS';
export const REVIEW_CREATED_ERROR = 'REVIEW_CREATE_ERROR';
//user types
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';
//error types
export const ERRORS_GET = 'ERRORS_GET';
export const ERRORS_CLEAR = 'ERRORS_CLEAR';
//order types
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATED_SUCCESS = 'ORDER_CREATED_SUCCESS';
export const ORDER_CREATED_ERROR = 'ORDER_CREATED_ERROR';
export const ORDER_SAVE_STORE = 'ORDER_SAVE_STORE';
